url: "http://www.eol.org"
browser: "chrome"

paths :
  'the home\s?page'       : '/'
  'preferences'           : '/settings?return_to=/'
  'the login page'        : '/login?return_to=/'

selectors :
  'the search button'     : '.search_image'
  'the search field'      : 'q'
  
  'a name search'    : 'search_type_names'
  'a tag search'     : 'search_type_tag'
  'a fulltext search' : 'search_type_google'
  
  'the username field'    : 'user_username'
  'the password field'    : 'user_password'
  'the login button'      : '#full-page-content input[type="submit"]'

  'the play button'       : 'play-button'
  'the pause button'      : 'play-button'
  'play'                  : 'play'
  'pause'                 : 'pause'
  'first explore'         : 'top_image_tag_1'
