'the home\s?page'       : '/'
#'the home[ ]?page'     : '/'
'preferences'           : '/settings?return_to=/'
'the login page'        : '/login?return_to=/'
'the registration page' : '/register'
'the tiger page'        : '/pages/328674'
