'the search button'     : '.search_image'
'the search field'      : 'q'
'the username field'    : 'user_username'
'the password field'    : 'user_password'
'the register password field' : 'user_entered_password'
'the confirm password field' : 'user_entered_password_confirmation'
'the email address field' : 'user_email'
'the given name field'  : 'user_given_name'
'the family name field' : 'user_family_name'
'the login button'      : '#full-page-content input[type="submit"]'
'the play button'       : '#play-button'
'the pause button'      : '#play-button'
'play'                  : 'play'
'pause'                 : 'pause'
'name search'           : 'search_type_text'
'tag search'            : 'search_type_tag'

'fulltext search'       : 'search_type_google'
'first explore'         : 'top_image_tag_1'
'second explore'        : 'top_image_tag_2'
'third explore'         : 'top_image_tag_3'
'fourth explore'        : 'top_image_tag_4'
'fifth explore'         : 'top_image_tag_5'
'sixth explore'         : 'top_image_tag_6'

'Whats New'             : '#sidebar-b'
'news headlines'        : '.helplist>a'
'expanded news item'    : 'div[id^="news"][style^="display: block"]'
'the curator checkbox'  : 'curator_request'

'the Flash Error Message'   : '#flash-bad'
'the Flash Mask'        : '#exposeMask'
'the tag image link'      : 'large-image-tagging-button-popup-link'
'the Add Tag field'       : 'tag_value'
'Add This Tag button'      : '#add_data_object_tags_fields input[type="submit"]'
'the public image tags block' : '#public_data_object_tags'
'my tags block'         : '#my_data_object_tags'

'the image comment link'  : '#large-image-comment-button .popup-link .span_block'
'the text comment link'  : '#right_text_buttons_group .popup-link .span_block'
'the add new comment field' : 'comment[body]'
'the Post Comment button' : '#commentsContain .new_comment .post_comment'

'the comment count' : '#large-image-comment-button .popup-link .span_block'
'the image comment count' : '#large-image-comment-button .popup-link .span_block'
'the text comment count' : '#right_text_buttons_group .popup-link .span_block'
'the pagination' : '#commentsContain .pagination'

'the Add New Content link' : '#new_text_toc_text'
'the Add New Content toc button' : '#new_text_toc_button'
'the Add New Content content button' : '#new_text_content_button'
'the Add New Content field' : '#insert_text_popup_content'
'the Add New Content close button' : '#insert_text_popup .close-button'
'the Add New Content preview button' : '#insert_text_popup .popup-content input[type="button"]'
'the Add New Content confirm button' : '#insert_text_popup .popup-content input[type="submit"]'
