'the search button'     : '.search_image'
'the search field'      : 'q'
'the username field'    : 'user_username'
'the password field'    : 'user_password'
'the register password field' : 'user_entered_password'
'the confirm password field' : 'user_entered_password_confirmation'
'the email address field' : 'user_email'
'the given name field'  : 'user_given_name'
'the family name field' : 'user_family_name'
'the login button'      : '#full-page-content input[type="submit"]'
'the play button'       : '#play-button'
'the pause button'      : '#play-button'
'play'                  : 'play'
'pause'                 : 'pause'
'name search'           : 'search_type_text'
'tag search'            : 'search_type_tag'
'fulltext search'       : 'search_type_google'

'first explore'         : 'top_image_tag_1'
'second explore'        : 'top_image_tag_2'
'third explore'         : 'top_image_tag_3'
'fourth explore'        : 'top_image_tag_4'
'fifth explore'         : 'top_image_tag_5'
'sixth explore'         : 'top_image_tag_6'

'Whats New'             : '#sidebar-b'
'news headlines'        : '.helplist>a'
'expanded news item'    : 'div[id^="news"][style^="display: block"]'

'the curator checkbox'  : 'curator_request'
