'the search button'     : '.search_image'
'the search field'      : 'q'
'the username field'    : 'user_username'
'the password field'    : 'user_password'
'the login button'      : '#full-page-content input[type="submit"]'
'the play button'       : '#play-button'
'the pause button'      : '#play-button'
'play'                  : 'play'
'pause'                 : 'pause'
'name search'           : 'search_type_text'
'tag search'            : 'search_type_tag'
'fulltext search'       : 'search_type_google'

'first explore'         : 'top_image_tag_1'
'second explore'        : 'top_image_tag_2'
'third explore'         : 'top_image_tag_3'
'fourth explore'        : 'top_image_tag_4'
'fifth explore'         : 'top_image_tag_5'
'sixth explore'         : 'top_image_tag_6'


'the Flash Error Message'   : '#flash-bad'
'the Flash Mask'		: '#exposeMask'
